# Définition du thème
remote_theme: just-the-docs/just-the-docs

# Configuration générale de votre site
title: "FORGE Documentation"
description: "Documentation for the FORGE framework and projects built with it."
baseurl: "/OSCAR_Documentation"
url: "https://daddesign-projects.github.io"

# Activer la recherche (indispensable pour une doc)
search_enabled: true

# Options d'en-tête (liens vers votre GitHub)
aux_links:
  "See the code on GitHub":
    - "//github.com/daddesign-projects/OSCAR_Documentation/"

# Pied de page : lien pour éditer la page sur GitHub
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "//github.com/daddesign-projects/OSCAR_Documentation/"
gh_edit_branch: "main"

# Configuration des callouts
callouts_level: loud #quiet  # ou loud pour plus de contraste
callouts:
  note:
    color: purple
  warning:
    color: red
  tip:
    color: green
  highlight:
    color: yellow

plugins:
  - jekyll-remote-theme

extra_css:
  - /assets/css/custom.css